apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: mobileapp
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: mobileapp
  MAIL_HOST: mailpit
  MAIL_PORT: "1025"
  APP_BASE_URL: http://localhost:8080
  CORS_ORIGINS: "*"
  ADMIN_USERNAME: admin
  ADMIN_EMAIL: admin@mobileapp.com
